version: '3'
services:
  maplestory:
    network_mode: "host"
    image: chisbread/heavenms:test
    depends_on:
      - msdb
    environment:
      WAIT_HOSTS: localhost:3306
    volumes:
      - ./config.yaml:/mnt/config.yaml
    restart: unless-stopped
  msdb:
    network_mode: "host" 
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "heavenms"
      MYSQL_ROOT_PASSWORD: "chisbread"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./dbfiles:/var/lib/mysql
    restart: unless-stopped